import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 200,
    justifyContent: 'center',
    flexDirection: 'column',
    backgroundColor: 'white',
  },
  f_logo: {
    width: 25,
    height: 25,
  },
  a_logo: {
    width: 15,
    height: 15,
  },
  image: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: 250,
    height: 250,
    marginBottom: 50,
  },
  buttonContainer: {
    marginTop: 10,
    marginLeft: 40,
    marginRight: 40,
  },
  text: {
    textAlign: 'center',
  },
  textContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  alternativeLayoutButtonContainer: {
    margin: 20,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  buttonGreen: {
    backgroundColor: '#2FCC87',
    color: 'white',
    borderRadius: 5,
    padding: 12,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  buttonFacebook: {
    backgroundColor: '#3A5A97',
    borderRadius: 5,
    padding: 12,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonApple: {
    backgroundColor: 'black',
    borderRadius: 5,
    padding: 12,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  button: {
    backgroundColor: 'white',
    borderColor: '#2FCC87',
    borderWidth: 0.25,
    color: '#2FCC87',
    borderRadius: 5,
    padding: 12,
    marginBottom: 10,
    marginLeft: 40,
    marginRight: 40,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  buttonTextGreen: {
    color: '#2FCC87',
    fontWeight: 'bold',
  },
  link: {
    flexDirection: 'row',
    justifyContent: 'center',
    flex: -1,
    marginTop: 5,
    color: 'black',
    fontWeight: 'bold',
    alignItems: 'center',
  },
  imageSmall: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
    height: 100,
    marginBottom: 50,
  },
  overlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.9,
    backgroundColor: 'gray',
    flex: 1,
  },
});
