import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: null,
    height: null,
  },
  container: {
    flex: 2,
    backgroundColor: 'white',
    alignItems: 'center',
  },
  buttonContainer: {
    marginTop: 10,
    flex: 1,
    width: '75%',
  },
  title: {
    fontWeight: 'bold',
    fontSize: 20,
    textAlign: 'center',
    marginTop: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },

  image: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 200,
    height: 200,
    marginTop: 30,
    marginBottom: 50,
  },
  textContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  alternativeLayoutButtonContainer: {
    margin: 20,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  buttonGreen: {
    backgroundColor: '#2FCC87',
    color: 'white',
    borderRadius: 5,
    padding: 15,
    textAlign: 'center',
    alignItems: 'center',
  },
  bottom: {
    justifyContent: 'flex-end',
    alignItems: 'stretch',
    width: '150%',
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  buttonTextGreen: {
    color: '#2FCC87',
    fontWeight: 'bold',
  },
  link: {
    flexDirection: 'row',
    justifyContent: 'center',
    flex: -1,
    marginTop: 5,
    color: 'black',
    fontWeight: 'bold',
    alignItems: 'center',
  },
  sheetHeader: {
    backgroundColor: 'white',
    color: '#2FCC87',
    marginTop: 5,
    marginHorizontal: 10,
    alignItems: 'center',
    flex: 1,
  },
  switchStyle: {
    transform: [{scaleX: 0.7}, {scaleY: 0.6}],
    alignItems: 'center',
  },
  dateStyle: {
    alignItems: 'center',
    backgroundColor: 'white',
  },
  modal: {
    marginTop: '70%',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  modalBackground: {
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 1.0,
    shadowRadius: 200,
    flex: 1,
  },
  modalForeground: {
    flex: 1,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    backgroundColor: 'white',
  },
  modalButtonWhite: {
    backgroundColor: 'white',
    fontWeight: 'bold',
    color: '#8C8C8C',
    padding: 10,
    fontSize: 20,
  },
  text: {
    fontWeight: 'bold',
    color: '#8C8C8C',
  },
  textGreen: {
    backgroundColor: 'white',
    fontWeight: 'bold',
    color: '#2FCC87',
    padding: 10,
    fontSize: 20,
  },
  textDate: {
    fontWeight: 'bold',
    color: '#2FCC87',
    padding: 20,
    alignItems: 'center',
    textAlign: 'center',
    fontSize: 20,
  },
  textinput: {
    backgroundColor: '#f8f8f8',
    borderColor: '#f8f8f8',
    borderWidth: 1,
    height: 53,
    fontWeight: 'bold',
    padding: 10,
    paddingTop: 15,
    flexDirection: 'row',
    textAlignVertical: 'center',
    justifyContent: 'space-between',
  },
  textinputLight: {
    padding: 10,
    paddingTop: 15,
    backgroundColor: 'white',
    alignItems: 'stretch',
    borderColor: '#f8f8f8',
    borderWidth: 1,
    height: 53,
    textAlignVertical: 'center',
    fontWeight: 'bold',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.9,
    backgroundColor: 'gray',
  },
});
