import {StyleSheet} from 'react-native';
import {width, height, totalSize} from 'react-native-dimension';
export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: null,
    height: null,
  },
  imageSmall: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
    height: 100,
    marginBottom: 50,
  },
  overlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.9,
    backgroundColor: 'gray',
    flex: 1,
  },
  container: {
    flex: 1,
    paddingTop: 200,
    justifyContent: 'center',
    flexDirection: 'column',
    backgroundColor: 'white',
  },
  containerGray: {
    flex: 1,
    paddingTop: 200,
    justifyContent: 'center',
    flexDirection: 'column',
    backgroundColor: 'gray',
  },
  image: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: 250,
    height: 250,
    marginBottom: 50,
  },
  imageSmall: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    width: 100,
    height: 100,
    marginBottom: 50,
  },
  buttonContainer: {
    marginTop: 50,
  },
  text: {
    textAlign: 'center',
  },
  textContainer: {
    marginLeft: 40,
    marginRight: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  alternativeLayoutButtonContainer: {
    margin: 20,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  buttonGreen: {
    backgroundColor: '#2FCC87',
    color: 'white',
    borderRadius: 5,
    padding: 12,
    marginBottom: 10,
    marginLeft: 40,
    marginRight: 40,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  button: {
    backgroundColor: 'white',
    borderColor: '#2FCC87',
    borderWidth: 0.25,
    color: '#2FCC87',
    borderRadius: 5,
    padding: 12,
    marginBottom: 10,
    marginLeft: 40,
    marginRight: 40,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  buttonTextGreen: {
    color: '#2FCC87',
    fontWeight: 'bold',
  },
  buttonCenter: {
    backgroundColor: '#859a9b',
    borderRadius: 20,
    padding: 10,
    marginBottom: 20,
    marginRight: 110,
    marginLeft: 110,
    shadowColor: '#303838',
    shadowOffset: {width: 0, height: 5},
    shadowRadius: 10,
    shadowOpacity: 0.35,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  link: {
    flexDirection: 'row',
    justifyContent: 'center',
    flex: -1,
    marginTop: 5,
    color: '#2FCC87',
    fontWeight: 'bold',
    textDecorationLine: 'underline',
    alignItems: 'center',
  },
});
